-- tabela usuarios

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  perfil ENUM('ALUNO','PROFESSOR') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela cursos
CREATE TABLE IF NOT EXISTS cursos (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT,
  caminho_imagem VARCHAR(512),
  professor_id BIGINT NOT NULL,
  CONSTRAINT fk_curso_professor FOREIGN KEY (professor_id) REFERENCES usuarios(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- tabela matriculas
CREATE TABLE IF NOT EXISTS matriculas (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  aluno_id BIGINT NOT NULL,
  curso_id BIGINT NOT NULL,
  data_matricula DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_matricula_aluno FOREIGN KEY (aluno_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT fk_matricula_curso FOREIGN KEY (curso_id) REFERENCES cursos(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
